### PR TITLE
fix: use default branch instead of master

### LINKED ISSUE #680: Add support for referencing a specific branch
Currently, all GitHub sources are retrieved from the master branch.

I want to use the reference to other commits, branches, and tags.

e.g. `[github/gitignore#main]`

If this feature is okay to add, I will send a PR.

### PR DESCRIPTION
**Pull request by risu729**
Closes #680

Uses the default branch of the repo retrieved from GitHub API instead of `master`.

Also adds support for specifying a commit/branch/tag with the syntax of #ref.

However, the API has a rate limit of 60 requests/hour. I used memoization to reduce requests, but if a user uses many repositories as a source or runs ignore-sync many times, the request might fail.

---

I skipped the `jest` pre-commit check since it didn't work with an error, "Validation Error: Preset @foray1010 not found."

### CODE REVIEW

File: src/cleanupIgnoreSyncFile.js [hunk 1]
```diff
@@ -3,9 +3,10 @@ import * as R from 'ramda'
 import { COMMENT_CHAR, LINE_BREAK } from './constants.js'
 
 const removeEmptyLines = R.reject((line) => line === '')
-const removeTrailingSpacesAndComment = R.replace(
-  new RegExp(`\\s*(${COMMENT_CHAR}.*)?$`),
-  '',
+const removeTrailingSpacesAndComment = R.ifElse(
+  R.test(/^\[(.*)\]/),
```
Comment (foray1010) [inline src/cleanupIgnoreSyncFile.js:7]: Nice thought 👍🏼

**Review by foray1010 — APPROVED** [review]

**Comment by risu729** [comment]
Thank you for your kindful support!
